#!/usr/bin/env bash
set -euo pipefail

# Builds lore-data.js from the actual lore repository using jq on the JSON files.
# The generated JS file is loaded by lore-explorer.html.
#
# Usage: ./tools/build-explorer-data.sh
# Output: ./lore-data.js

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
BOOKS_DIR="${BOOKS_DIR:-$REPO_ROOT/knowledge/expanded/lore/books}"
ENTRIES_DIR="${ENTRIES_DIR:-$REPO_ROOT/knowledge/expanded/lore/entries}"
PERSONA_DIR="${PERSONA_DIR:-$REPO_ROOT/knowledge/expanded/personas}"
OUTPUT="$REPO_ROOT/lore-data.js"

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

echo "Building lore explorer data..."

# Step 1: Build books array -> temp file
(
  for book_file in "$BOOKS_DIR"/*.json; do
    [[ ! -f "$book_file" ]] && continue
    entry_count=$(jq -r '.entries | length' "$book_file")
    (( entry_count == 0 )) && continue
    jq -c '{
      id: .id,
      title: .title,
      desc: .description,
      date: (.metadata.created_at // "" | split("T")[0]),
      status: (.metadata.status // "draft"),
      entry_ids: .entries,
      readers: (.readers // []),
      owners: (.owners // [])
    }' "$book_file"
  done
) | jq -s '.' > "$TMP_DIR/books.json"

echo "  Found $(jq 'length' "$TMP_DIR/books.json") non-empty books"

# Step 2: Build entries array -> temp file
(
  for entry_file in "$ENTRIES_DIR"/*.json; do
    [[ ! -f "$entry_file" ]] && continue
    jq -c '{
      id: .id,
      title: .title,
      content: .content,
      cat: .category,
      tags: (.tags // []),
      book_id: (.book_id // ""),
      relationships: (.relationships // []),
      date: (.metadata.created_at // "" | split("T")[0])
    }' "$entry_file"
  done
) | jq -s '.' > "$TMP_DIR/entries.json"

echo "  Found $(jq 'length' "$TMP_DIR/entries.json") entries"

# Step 3: Build personas array -> temp file
(
  for persona_file in "$PERSONA_DIR"/*.json; do
    [[ ! -f "$persona_file" ]] && continue
    jq -c '{
      id: .id,
      name: .name,
      traits: (.core_traits // {}),
      voice: (.voice // {}),
      lore_books: (.knowledge.lore_books // []),
      date: (.metadata.created_at // "" | split("T")[0])
    }' "$persona_file"
  done
) | jq -s '.' > "$TMP_DIR/personas.json"

echo "  Found $(jq 'length' "$TMP_DIR/personas.json") personas"

# Step 4: Combine into single JS file using jq --slurpfile
cat > "$OUTPUT" << 'HEADER'
// Auto-generated by tools/build-explorer-data.sh
// Regenerate with: ./tools/build-explorer-data.sh
window.LORE_DATA =
HEADER

jq -n \
  --slurpfile books "$TMP_DIR/books.json" \
  --slurpfile entries "$TMP_DIR/entries.json" \
  --slurpfile personas "$TMP_DIR/personas.json" \
  '{books: $books[0], entries: $entries[0], personas: $personas[0]}' >> "$OUTPUT"

echo ";" >> "$OUTPUT"

total_size=$(wc -c < "$OUTPUT")
echo "  Written to $OUTPUT ($(( total_size / 1024 ))KB)"
echo "Done."
